[Refactor] Add support for "dtype" (KV cache storage data type) in LMCacheEngineMetadata
LMCache/lmcache-vllm pull request #10
Opened 2024-09-24 16:25 UTC by Alex-q-z

This PR resolves issue #103 in the LMCache repo.

2024-10-01 15:48 UTC, KuntaiDu requested changes, later dismissed

2024-10-01 15:48 UTC, KuntaiDu commented on lmcache_vllm/vllm_injection.py
> +    }
Maybe also add support to other DTYPEs (e.g. torch.float16, torch.float8_e4m3fn, torch.float8_e5m2)

2024-10-01 15:48 UTC, KuntaiDu commented on lmcache_vllm/vllm_injection.py
> +    # enforce KV cache dtype to be str + non-auto
This comment is a bit hard to read. Do you mean "KV cache dtype to be the same as vLLM KV cache dtype" or something?

2024-10-08 05:17 UTC, Alex-q-z commented on lmcache_vllm/vllm_injection.py
> +    }
Fixed in [37d0833](https://github.com/LMCache/lmcache-vllm/pull/10/commits/37d0833730bf502ded1c77bedab52c415d93e1be).

2024-10-08 05:17 UTC, Alex-q-z commented on lmcache_vllm/vllm_injection.py
> +    # enforce KV cache dtype to be str + non-auto
Fixed in [37d0833](https://github.com/LMCache/lmcache-vllm/pull/10/commits/37d0833730bf502ded1c77bedab52c415d93e1be).

2024-10-08 09:44 UTC, ApostaC requested changes
Thanks, Qizheng! Just one comment.

2024-10-08 09:44 UTC, ApostaC commented on lmcache_vllm/vllm_injection.py
> +        self.cache_config.cache_dtype = TORCH_DTYPE_TO_STR_DTYPE[kv_cache_type]
Will this change the values in the vLLM's configuration? It would be better to treat `self.cache_config` as "read only". Maybe make a copy and then change the `cache_dtype` before passing to `init_lmcache_engine`?

2024-10-18 19:33 UTC, ApostaC approved these changes, later dismissed
LGTM! Thanks!

2024-10-22 15:48 UTC, ApostaC approved these changes
LGTM! Please merge

2024-10-22 15:51 UTC, merged